### ISSUE TITLE
Корректировки шаблона места,  раздел про старты

### ISSUE THREAD

**Issue by gh0s7ik** [gh0s7ik/parawiki#30]
Дима:
Наверное в табличку старта нужно добавить прямо пункт - что проверяют при входе на старт или платность/бесплатность.
И в шаблон сразу два старта добавить. Самому не понятно, в какое место вставлять копию старта для второго, долго думаю.

**Comment by Dmitry-Borodin** [comment]
1) В табличке старта убрать топлендинг - его можно описать в разделе завоза там, где завоза нет.
2)Из таблички убрать штатную посадку, добавить раздел с посадками ниже
3)В маршрутный потенциал перенести ссылку на хцконтест как у места, но ровно на старт. Убрать штатные цифры с 50км - т.к. раз в жизни откуда угодно на 50км кто-то случайно улетает - этот параметр слишком субъективен.
4)Убрать строчку с очередями. Не понятно, что туда писать, потому что от раза к разу очень разные бывают очереди.

**Comment by gh0s7ik** [comment]
- [x] добавить с таблицу старта пункт - что проверяют при входе на старт => в отдельный тикет
- [x] добавить в таблицу старту пункт платность/бесплатность => в отдельный тикет
- [x] в шаблон сразу два старта добавить. Самому не понятно, в какое место вставлять копию старта для второго
- [x] В табличке старта убрать топлендинг - его можно описать в разделе завоза там, где завоза нет. => оставляем пока
- [x] Из таблички убрать штатную посадку, добавить раздел с посадками ниже => оставляем сверхувнизную в таблице
- [x] В маршрутный потенциал перенести ссылку на хцконтест как у места, но ровно на старт. Убрать штатные цифры с 50км - т.к. раз в жизни откуда угодно на 50км кто-то случайно улетает - этот параметр слишком субъективен.
- [x] Убрать строчку с очередями. Не понятно, что туда писать, потому что от раза к разу очень разные бывают очереди.
- [x] (???) перенести раздел "Опасности" ПЕРЕД разделом "Старты"

-----

- [x] обновить шаблон
- [x] обновить страницы

**Comment by gh0s7ik** [comment]
Вопросы про платность и пермиты будем обсуждать позже и здесь: https://github.com/gh0s7ik/parawiki/issues/31

Остальное исправлено или решено не исправлять.
